version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mmc
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data-mysql:/var/lib/mysql
volumes:
  data-mysql:
    external: true
